# Generated by Django 5.2.12 on 2026-04-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateJoined', models.DateField()),
                ('position', models.CharField(choices=[('S', 'Setter'), ('L', 'Libero'), ('MH', 'Middle Hitter'), ('OP', 'Opposite Hitter'), ('OH', 'Outside Hitter'), ('DS', 'Defensive Specialist')], max_length=3)),
                ('salary', models.DecimalField(decimal_places=4, max_digits=10)),
                ('contactPerson', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
